modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="kruemblegard"
version="${file.jarVersion}"
displayName="Krümblegård"
description='''
Ancient megalithic stone guardian bound by cursed runes.
'''

[[dependencies.kruemblegard]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.kruemblegard]]
modId="geckolib"
mandatory=true
versionRange="[4.4.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.kruemblegard]]
modId="waystones"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.kruemblegard]]
modId="waystoneinjector"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="CLIENT"
