modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="krumblegard"
version="${file.jarVersion}"
displayName="Kr체mbleg책rd"
description='''
Kr체mbleg책rd, Warden of the Standing Circle.
'''

[[dependencies.krumblegard]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.krumblegard]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.krumblegard]]
modId="geckolib"
mandatory=true
versionRange="[4,)"
ordering="NONE"
side="BOTH"

[[dependencies.krumblegard]]
modId="waystones"
mandatory=true
versionRange="[14.1.17,)"
ordering="NONE"
side="BOTH"
